default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: fh17794.sa-east-1.aws
      user: DESAFIOFINALLH                          
      password: "{{ env_var('DB_PASSWORD') }}"          
      warehouse: COMPUTE_WH                 
      database: DESAFIO_LH                      
      schema: DESAFIO_LH                            
      role: ACCOUNTADMIN                         
      threads: 4                                
      authenticator: snowflake                   
      
